In [ ]:
# Здравствуйте!

# Задание 1:
# Даны значения величины заработной платы заемщиков банка (zp) и 
# значения их поведенческого кредитного скоринга (ks):
# zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
# ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
# Найдите ковариацию этих двух величин с помощью элементарных действий, 
# а затем с помощью функции cov из numpy
# Полученные значения должны быть равны.
# Найдите коэффициент корреляции Пирсона с помощью ковариации и 
# среднеквадратичных отклонений двух признаков,
# а затем с использованием функций из библиотек numpy и pandas.





In [12]:
import numpy as np
import pandas as pd
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])




In [6]:
cov=np.mean(zp*ks)-np.mean(zp)*np.mean(ks)
cov

9157.839999999997

In [8]:
np.cov(zp,ks,ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [ ]:
# 9157,84 = 9157,84

In [9]:
np.std(zp)

59.115480206118605

In [10]:
np.std(ks)

174.55340157098058

In [11]:
r = (np.cov(zp,ks,ddof=0))/(np.std(zp)*np.std(ks))
r

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [13]:
np.corrcoef(zp,ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [ ]:
#0.88749009 = 0.88749009 

In [ ]:
# Задание 2:
# Измерены значения IQ выборки студентов,
# обучающихся в местных технических вузах:
# 131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
# Известно, что в генеральной совокупности IQ распределен нормально.
# Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [14]:
iq=np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
iq

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [20]:
s = np.std(iq)
s

10.004498987955369

In [21]:
mu = np.mean(iq)
mu

118.1

In [ ]:
mu + (2,262 * s)/np.sqrt(10)

In [ ]:
mu - (2,262 * s)/np.sqrt(10)

In [ ]:
#Ответ: [110,94:125,25] при а = 0,05

In [ ]:
# Задание 3:
# Известно, что рост футболистов в сборной распределен нормально
# с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
# среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
# ожидания с надежностью 0.95.

In [ ]:
174,2 + (1,96 * 25)/np.sqrt(27)

In [ ]:
174,2 - (1,96 * 25)/np.sqrt(27)

In [ ]:
# Ответ: [164,77:183,63] при а = 0,05